@baseUrl = http://localhost:3001/api/v1

###
GET http://localhost:3001/health

###
GET {{baseUrl}}/symptoms

###
GET {{baseUrl}}/diseases

###
GET {{baseUrl}}/rules

###
POST {{baseUrl}}/diagnose
Content-Type: application/json

{
  "symptoms": [
    { "symptom_id": "S006", "certainty": 1.0 },
    { "symptom_id": "S007", "certainty": 1.0 }
  ]
}

###
GET {{baseUrl}}/feedback

###
POST {{baseUrl}}/feedback
Content-Type: application/json

{
  "name": "Christo",
  "notes": "Prediksi meleset",
  "category": "keluhan"
}

###
GET {{baseUrl}}/stats

